### PR TITLE
Add FileOutput.finish() in Provider.finish()

### PR DESCRIPTION
**Pull request by chikamura**
FileOutput.finish() should be called in CommonsCompressArchiveProvider.finish(), because some plugins (ex. [embulk-output-sftp](https://github.com/embulk/embulk-output-sftp)) doesn't work properly.

### CODE REVIEW

**Comment by hata** [comment]
Thank you very much for filing this pull request, too. I will review the request.

**Comment by chikamura** [comment]
Many Thanks!

**Comment by hata** [comment]
FYI: I also pushed gem to rubygems as v 0.2.0. Please check the latest gems if needed.
Thanks again!

**Comment by chikamura** [comment]
@hata 
I am terribly sorry. Today's PRs have a bug when using archive format.
Please could you check [this PR](https://github.com/hata/embulk-encoder-commons-compress/pull/7)?

**Comment by hata** [comment]
@chikamura Thank you for reporting the issue you found. I will check your suggested PR. Thanks!

**Pull request merged**
